### ISSUE TITLE
Fråga om pull request regel

### ISSUE THREAD

**Issue by stonetwig** [kodsnack/advent_of_code_2016#1]
Hej Kodsnack,

Hade tänkt vara med i år och kan väl förhoppningsvis dra med mig ett par andra också.
Men jag undrar om man kan skapa en PR redan efter första dagen och och sedan uppdatera med commits eller måste man skapa en PR tidigast den 25e?

Mvh M

**Comment by bjoreman** [comment]
Vi får nog förtydliga det, det går givetvis bra att göra requests allt eftersom. Ju mer och tidigare man kan se varandras kod desto bättre ju! Den första request som avslutar alla dagar och gör lösningarna korrekta vinner, är väl vad vi försökte säga. (Om det nu blev så mycket tydligare 😋)

Vänliga hälsningar,
Kodsnack via Fredrik Björeman
