### ISSUE TITLE
En eller två lösningar per dag

### ISSUE THREAD

**Issue by tomasskare** [kodsnack/advent_of_code_2016#8]
Eftersom årets AoC har två uppgifter per dag, behöver båda uppgifterna lösas för tävlingen, eller räcker det med första uppgiften varje dag?

**Comment by estomagordo** [comment]
Den andra uppgiften är ju alltid mer komplex, så jag vet inte varför man skulle begränsa sig till den första.

**Comment by martinsvalin** [comment]
Rimligen får man väl skicka in vad man vill. Ska man vara med och tävla så är det först till 50 stjärnor. Men man kan ju delta för att det är roligt också, utan att ha några ambitioner att vinna priser.

**Comment by bjoreman** [comment]
Ja, båda lösningarna för varje dag om man vill vinna. Helt fri form annars, såklart :-) …
